# # ####
# equity_0p03:
#   approxRiskyDstn: 'lambda count: approxNormal(count, mu = 0.03 + 1.02, sigma = 0.157)'

# equity_0p015:
#   approxRiskyDstn: 'lambda count: approxNormal(count, mu = 0.015 + 1.02, sigma = 0.157)'

# equity_0p0075:
#   approxRiskyDstn: 'lambda count: approxNormal(count, mu = 0.0075 + 1.02, sigma = 0.157)'

# short_career:
#   Age_born: 20
#   Age_retire: 40
#   Age_death: 40
#   age_plot_params: [25, 30, 35]

# random_shocks:
#   Age_born: 22
#   Age_retire: 55
#   Age_death: 80
#   TranShkStd: np.random.randint(600, 1600, size=58)/10000
#   PermShkStd: np.random.randint(300, 700, size=58)/10000

Parameters_base:
  Age_born: 20
  Age_retire: 65
  Age_death: 100

# Parameters_1940s_shocks:
#   Age_born: 27
#   Age_retire: 65
#   Age_death: 100
#   TranShkStd: np.array([0.063 , 0.066 , 0.0675, 0.0685, 0.069 , 0.069 , 0.067 , 0.0665, 0.066 , 0.064 , 0.063 , 0.062 , 0.061 , 0.06  , 0.0585, 0.057 , 0.055 , 0.053 , 0.0515, 0.05  , 0.047 , 0.045 , 0.043 , 0.04  ,0.038 , 0.036 , 0.033 , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  ,0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  ,0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  , 0.03  ])
#   PermShkStd: np.array([0.15 , 0.122, 0.115, 0.105, 0.093, 0.09 , 0.087, 0.08 , 0.075, 0.075, 0.067, 0.068, 0.061, 0.062, 0.058, 0.06 , 0.058, 0.058, 0.057, 0.056, 0.054, 0.057, 0.059, 0.059, 0.063, 0.066, 0.07 , 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073,0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073,0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073, 0.073])
#   age_plot_params: [30, 40, 50, 60, 70, 80]
